/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import components.IValue;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import view.factory.PersonViewFactory;
import view.factory.impl.AdvancedPersonViewFactory;
import view.factory.impl.AdvancedPersonViewFactoryv2;
import view.factory.impl.SimplePersonViewFactory;

/**
 *
 * @author Nikola
 */
public class FrmPerson extends javax.swing.JPanel {

    /**
     * Creates new form frmPerson
     */
    public FrmPerson() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputComboBox = new components.fields.PanelInputComboBox();
        btnSubmit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        panelPerson = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(440, 320));

        inputComboBox.setPreferredSize(new java.awt.Dimension(440, 64));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        panelPerson.setBorder(javax.swing.BorderFactory.createTitledBorder("Person"));
        panelPerson.setPreferredSize(new java.awt.Dimension(440, 263));
        panelPerson.setVerifyInputWhenFocusTarget(false);
        panelPerson.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(btnConfirm))
            .addComponent(panelPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(btnSubmit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addGap(8, 8, 8)
                .addComponent(panelPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String personString = "";
        Component[] components = ((JPanel) panelPerson.getComponent(0)).getComponents();
        for (Component component : components) {
            if (component instanceof IValue) {
                personString += ((IValue) component).getValue() + " ";
            }
        }
        JOptionPane.showMessageDialog(this, personString);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        inputComboBox.getLblError().setText("");
        inputComboBox.getLblError().setVisible(false);
        switch ((String) inputComboBox.getValue()) {
            case "F1":
                panelPerson.removeAll();
                PersonViewFactory factory = new AdvancedPersonViewFactoryv2();
                panelPerson.add(factory.getPersonView());
                panelPerson.revalidate();
                panelPerson.repaint();
                break;
            case "F2":
                panelPerson.removeAll();
                factory = new AdvancedPersonViewFactory();
                panelPerson.add(factory.getPersonView());
                panelPerson.revalidate();
                panelPerson.repaint();
                break;
            case "F3":
                panelPerson.removeAll();
                factory = new SimplePersonViewFactory();
                panelPerson.add(factory.getPersonView());
                panelPerson.revalidate();
                panelPerson.repaint();
                break;
            default: {
                try {
                    throw new Exception("Invalid input option!");
                } catch (Exception ex) {
                    inputComboBox.getLblError().setText(ex.getMessage());
                }
            }
        }
        btnSubmit.setVisible(true);
    }//GEN-LAST:event_btnConfirmActionPerformed
    private void prepareView() {
        prepareCombo();
        btnSubmit.setVisible(false);
    }

    private void prepareCombo() {
        List<String> options = new ArrayList<>();
        options.add("F1");
        options.add("F2");
        options.add("F3");
        inputComboBox.initialize(options);
        inputComboBox.getLblFieldText().setText("Input options:");
        inputComboBox.getLblError().setText("Please choose input option");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSubmit;
    private components.fields.PanelInputComboBox inputComboBox;
    private javax.swing.JPanel panelPerson;
    // End of variables declaration//GEN-END:variables

}
